### ISSUE TITLE
can not access to the whole project

### ISSUE THREAD

**Issue by ThousandOfWind** [HumanCompatibleAI/human_aware_rl#2]
$ git clone --recursive git@github.com:HumanCompatibleAI/human_aware_rl.git:
Cloning into 'human_aware_rl'...
Permission denied (publickey).
fatal: Could not read from remote repository.

also it is fail when directly downloading ZIP from the web 

What happened?

**Comment by micahcarroll** [comment]
Thanks for reaching out! I'll look into this and get back to you soon!

**Comment by micahcarroll** [comment]
Hi @ThousandOfWind, 

I believe your issue might be due to not having a public key linked to your github account – referring to https://help.github.com/articles/connecting-to-github-with-ssh/ might help.

In any case, I am updating the README to have HTTPS cloning commands rather than SSH ones, so that these should now work for you (even without following the steps above).

Best,
Micah

**Comment by ThousandOfWind** [comment]
Thank U very much!
