### ISSUE TITLE
NOTICE: HUMAN BEHAVIOUR CLONED ON DIFF ENV

### ISSUE THREAD

**Issue by LauraRuis** [HumanCompatibleAI/human_aware_rl#22]
_Context for the question_: I'm trying to re-produce the behavior cloning results from [the 2019 NeurIPS paper](https://arxiv.org/abs/1910.05789) in PyTorch, and even though it works with the old MDP (reproduces similar scores when evaluated with two behavior-cloned agents), it doesn't with the new MDP (the agents keep waiting for a soup to finish that never even starts cooking, sometimes they accidentally trigger it and it starts cooking and they get some reward).

Seems like the overcooked-ai MDP worked differently when collecting the human data for NeurIPS 2019 paper than it does now.
If you look at the part of the MDP that is used now in `overcooked-ai/mdp/overcooked_mdp.py` line 168 (https://github.com/HumanCompatibleAI/overcooked_ai/blob/7e774a1aa29c28b7b69dc0a8903822ac2c6b4f23/src/overcooked_ai_py/mdp/overcooked_mdp.py#L1168)

You see that after you put all the ingredients in the pot, you need an extra "interact" action without holding an object to get the soup to start cooking.

But if you compare that same logic in the MDP that was used for the NeurIPS paper (https://github.com/HumanCompatibleAI/overcooked_ai/blob/6eaceb0a9a2501f1b9fccbf4c7016d6662ed1108/overcooked_ai_py/mdp/overcooked_mdp.py#L821)

you see in line 821 you see that the cook time gets incremented everytime step_environment_effects() is called and there is a soup object at the P terrain that has the right number of items, i.e. no interact necessary.

I also looked at the trajectories in the human data pickles from 2019, and there the cooking time always just jumps to 1 after the final onion is added without an extra interact action.

Was wondering a couple of things:

- why was this MDP change made?
- What do you think would be best for reproducing the PPO + BC results in the paper:
1. use the old environment for the BC agents
2. add some hardcoded data augmentation where we add an extra interact between the final state with cooking_tick = -1 and cooking_tick = 1
3. something else?

Thanks!

**Comment by rohinmshah** [comment]
I don't know about why this change was made, but I am fairly confident that
if you want to reproduce the PPO + BC results as closely as possible you
would want the old environment where you didn't need this extra interact
action.

Micah would have more information on the other questions; hopefully he'll
answer soon.

**Comment by micahcarroll** [comment]
Rohin is right in that to use the old data, the best/simplest way would be to use the old version of the MDP (because, as you have found, the data is missing a key action – the "interact" to cause a soup to start cooking) – that is, option (1) that you delineate. It may be possible to do option (2), either by modifying the data as you suggest, or by simply modifying the new code to not require the _interact_ action anymore for initiating cooking (this assumes you will only be using 3-item soups, as in the original paper – as explained below).

For more context on why the dynamics were changed: in the original environment, given that all soups had 3 items (3 onions), the _initiate cooking_ step could be abstracted away (as it doesn't make sense in any circumstance to start cooking the soup before you reach 3 items, and it always makes sense once you have 3 items, so we had it cooking start automatically when 3 onions were in the pot). However, for a follow-up project we were interested in experimenting with more complex soups (using both tomatoes and onions), that could be composed of a variable amount of ingredients (1-item, 2-item, 3-item soups). To be able to start the cooking process of a 1-item soup, there had to be an additional step, that would differentiate that from having placed just one item in the pot with the intention of adding another couple of items before starting the cooking.

We do have some human data collected [with the updated dynamics](https://github.com/HumanCompatibleAI/human_aware_rl/tree/master/human_aware_rl/static/human_data), but it's on a different subset of layouts.

Hope this helps!

**Comment by akbir** [comment]
Thanks for the quick response @micahcarroll and @rohinmshah, the clarity over why the MDPs changed is super useful!

I think it would be good to sign the change in environment dynamics on the (env repo)[ https://github.com/HumanCompatibleAI/overcooked_ai]. Some versioning would help us refer to the changes in the environment.

Not sure what'll we decide yet -  but if we do try use the new BC data we'll share results with you!

**Comment by LauraRuis** [comment]
Thanks a lot both!

**Comment by micahcarroll** [comment]
Yeah, I agree that better versioning would help! We will have a full-time research engineer relatively soon working on this repo (likely on the order of weeks), so I'll have them do this. As a temporary solution, for the "old-dynamics" version of the environment, I would refer to the Overcooked-AI [commit](https://github.com/HumanCompatibleAI/overcooked_ai/tree/6eaceb0a9a2501f1b9fccbf4c7016d6662ed1108) that is linked from the neurips2019 branch of human_aware_rl.

**Comment by apurl1** [comment]
Somewhat related- what is the correct way to create a BC agent using the main branch? Using AgentFromPolicy with the BehaviorCloningPolicy class seems to be an issue because the multi_state_policy method is not defined in the latter.

**Comment by micahcarroll** [comment]
Hi @apurl1, sorry for the very slow response. Have you taken a look at the BC [tests](https://github.com/HumanCompatibleAI/human_aware_rl/blob/master/human_aware_rl/imitation/behavior_cloning_tf2_test.py)? This might be a useful pointer for how the classes are supposed to be used.
